strategy:
  name: "Nancy Pelosi CHIPS Strategy"
  initial_amount: "$10,000"
  benchmark: "SPY"

data_source:
  api_url: "http://127.0.0.1:8000"  # data-service URL Change to actual deployment URL after
  lookback: "3Y"  # Historical data lookback period

performance:
  risk_free_rate: 0.02  # 2% risk-free rate for Sharpe calculation